apiVersion: v1beta
kind: Secret
metadata:
  name: docker-hub
data:
  env_vars:
    - name: DOCKER_USERNAME
      value: "dusanov"
    - name: DOCKER_PASSWORD
      value: "ba17362a-acc5-4949-a064-14dcc5820e65"
